spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "component-imports-example"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "service"

[component.service]
# environment = { CLIENT_ID = "CLIENT_ID", SECRET = "SECRET" }
source = "service.wasm"
[component.service.imports."wasi:http/incoming-handler@0.2.0-rc-2023-10-18"]
component = "handler"
export = "wasi:http/incoming-handler@0.2.0-rc-2023-10-18"

# component = "handler"
# export = "wasi:http/incoming-ha

[component.handler]
# environment = { ... }
source = "handler.wasm"