[package]
name = "greet"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cargo-component-bindings = "0.4.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:greet"

[package.metadata.component.dependencies]
